# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'



target 'CloudyLove' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudyLove

  # Animation Pod
  pod 'Spring'#, :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'

  target 'CloudyLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudyLoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
