# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Firebase Pods
pod 'Firebase/Core'
pod 'Firebase/Database'

target 'FirebaseLesson' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseLesson

  target 'FirebaseLessonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
